import { ThemeProvider } from '@/components/ui/theme';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import Navbar from '@/components/Navbar';
import ContextProvider from '@/components/ui/contex';
import { headers } from 'next/headers'; // added

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookies = headers().get('cookie');
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					forcedTheme="light"
				>
					<ContextProvider cookies={cookies}>
						<Navbar />
						{children}
					</ContextProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
